### ISSUE TITLE
Long user input

### ISSUE THREAD

**Issue by oliverjam** [fac19/week8-TheElite4#29]
It looks like you've tested lots of kinds of input, which is great. There's a really long title that's breaking the layout and causing horizontal scrolling.

You can control this with something like:

```css
h2 {
    word-wrap: break-word;
}
```

to force it to wrap when it hits the edge of the container
